### ISSUE TITLE
Sql Server 2017 support?

### ISSUE THREAD

**Issue by KJJK** [ASStoredProcedures/ASStoredProcedures#1]
Hi,
we use this amazing tool for comparing the structure of SSAS with the relational structure and need this tool for sql server 2017.
Are there any plans in updating the latest version?

**Comment by AdamTheDestroyer** [comment]
#Push# We need this great tool too for SQL Server 2017. Please make a new release.

**Comment by BenniDeJagere** [comment]
Yes please!

**Comment by dgosbell** [comment]
I've just added a pre-release with [2017 support](https://github.com/ASStoredProcedures/ASStoredProcedures/releases/tag/1.4.3.alpha) can you please check that it works for you. There is no new functionality, it's just been recompiled against the 2017 references.

**Comment by BenniDeJagere** [comment]
I've just tested the pre-release on our DEV SSAS 2017 box. Works like a charm!

Thanks a million!

**Comment by dgosbell** [comment]
Great, thanks for letting us know
