### ISSUE TITLE
when is avaiable dll for SQL Analisy Serivces 2017 ?

### ISSUE THREAD

**Issue by marcoangel61** [ASStoredProcedures/ASStoredProcedures#2]
when is avaiable dll for SQL Analisy Serivces 2017 ?

**Comment by AdamTheDestroyer** [comment]
#Push# We need this great tool too for SQL Server 2017. Please make a new release.

**Comment by dgosbell** [comment]
I've just added a pre-release with [2017 support](https://github.com/ASStoredProcedures/ASStoredProcedures/releases/tag/1.4.3.alpha) can you please check that it works for you. There is no new functionality, it's just been recompiled against the 2017 references.
