### ISSUE TITLE
Error running under SSAS 2012

### ISSUE THREAD

**Issue by mitcharoni** [ASStoredProcedures/ASStoredProcedures#3]
I've tried registering the DLL and I've also used the XMLA for various versions and I keep getting the same error message:

Execution of the managed stored procedure ClearCache failed with the following error: Exception has been thrown by the target of an invocation. Could not load file or assembly 'Microsoft.AnalysisServices, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

It doesn't matter which function I run.

I'm using SSMS 2012 on the server. Server version is SQL 2012 (11.0.6020.0).

**Comment by furmangg** [comment]
Which file did you deploy? ASSP_2012 or ASSP_2008?

**Comment by mitcharoni** [comment]
I tried ASSP_2012, ASSP_2014, and ASSP_2016. I tried all three with the XMLA; I only tried 2012 with the .dll. All versions were the 1.4.2 release.

Both ASSP_2012 and ASSP_2014 gave me the same message above. ASSP_2016 gave me the same message but referenced the 13.0.0.0 version of Microsoft.AnalysisServices instead. Otherwise, the error message was the same. I was just trying to see if anything worked.

**Comment by mbitiutskyi** [comment]
It seems like 2008, 2012 and 2014 versions (both dlls and xmlas) are the same, Taking into account the version of necessary ADOMD component I suppose 2012/2014 are copies of 2008 build. Is it possible to reload proper versions of 2012 and 2014 to repository? Thank in advance)

**Comment by vincyf1** [comment]
Has this been resolved yet? I am getting similar error for SQL 2014 as well. 

_Execution of the managed stored procedure DiscoverXmlMetadataFull failed with the following error: Exception has been thrown by the target of an invocation.Could not load file or assembly 'Microsoft.AnalysisServices.Xmla, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified._

**Comment by affsantos** [comment]
I am having the same issue. Is this not yet resolved?

**Comment by dgosbell** [comment]
I've just added a pre-release where I've recompiled all the different versions [1.4.3 release](https://github.com/ASStoredProcedures/ASStoredProcedures/releases/tag/1.4.3.alpha) can you please check that it works for you. There is no new functionality, it's just been recompiled against the 2017 references. I've double checked the references using reflector and they seem to be targeting the correct versions of the dlls, but I do not current have access to 2012 or 2014 instances to test this on (hence the pre-release status)
