### ISSUE TITLE
Analysis Services 2017 and 2019 support

### ISSUE THREAD

**Issue by ykhabins** [ASStoredProcedures/ASStoredProcedures#4]
Please add support for the following SSAS versions:
- 2017
- 2019

**Comment by dgosbell** [comment]
I've just added a pre-release with [2017 support](https://github.com/ASStoredProcedures/ASStoredProcedures/releases/tag/1.4.3.alpha) can you please check that it works for you. There is no new functionality, it's just been recompiled against the 2017 references.

**Comment by furmangg** [comment]
Just added 2019 support in the same release Darren mentioned above
