### ISSUE TITLE
ASSP error :- No cube specified. A cube must be specified for this command to work.

### ISSUE THREAD

**Issue by Prince1805** [ASStoredProcedures/ASStoredProcedures#7]
Error while running the same in SSMS 
  call  ASSP.GetMeasureGroupCalculatedMeasures("Internet Sales")
![Error](https://user-images.githubusercontent.com/65440879/82113725-c6835c00-978a-11ea-90f3-119afe31b9eb.jpg)

**Comment by dgosbell** [comment]
You can't execute that method using CALL as it returns a set. You can only use CALL to execute functions that return rowsets, strings or void. 

As it mentions in the [documentation](https://asstoredprocedures.github.io/functions/Drillthrough/) that function is a helper function which is only designed to be used in the condition of a custom rowset action.

**Comment by Prince1805** [comment]
Thanks a lot @dgosbell as I am very new to SSAS world can you help me with an example how the script will look like....

**Comment by Prince1805** [comment]
Thanks a lot @dgosbell for responding. Actually i posted the wrong command, I will ask it differently for SSAS 2012 Drillthrough action I need to show current period and its parallel period data together. But I wasn't able to call custom MDX but was not able to even call the below assp procedure 

CALL ASSP.GetDefaultDrillthroughMDX([Measures].[Internet Sales-Sales Amount])

I know it's wrong but not sure how to call these functions. Apologies i am very new to SSAS and MDX world. Thanks a lot for helping.....

**Comment by dgosbell** [comment]
There a whole lot of examples and instructions in the documentation page I linked to in my last reply. When you use the GetDefaultDrillthroughMDX function in an action expression you don't use the CALL keyword.

**Comment by Prince1805** [comment]
Thanks @dgosbell , request if you can share with example end to end mdx query using the GetDefaultDrillthroughMDX function. As I am very new to MDX and have very limited knowledge so it will be of very great help and gives me starting point to work upon...

**Comment by furmangg** [comment]
To close off this thread, there are some documented examples here:
https://asstoredprocedures.github.io/functions/Drillthrough/

Notice carefully when and when not to use the CALL word in front of it and when it's used as an action definition.
