### ISSUE TITLE
Function does not exist ASSP.ExecuteSQL

### ISSUE THREAD

**Issue by bullsrl** [ASStoredProcedures/ASStoredProcedures#8]
Hi All,

I am testing out this Set of Stored Procedures for use with Rowset Drillthroughs I followed the Installation instructions with the zip files and the Assemblies now includes the ASSP, however when I run the test code against the cube I get the error:

Executing the query ...
Query (1, 6) The '[ASSP].[ExecuteSQL]' function does not exist.
Run complete

![image](https://user-images.githubusercontent.com/32177997/100925534-1e2baf80-34b0-11eb-8e31-f4453a2dbad8.png)

![image](https://user-images.githubusercontent.com/32177997/100925674-4ddab780-34b0-11eb-8cbb-3cf3a1e70fd9.png)

Any help would be appreciated as to why this might be the case?

Cheers

James

**Comment by dgosbell** [comment]
This is because ExecuteSQL is not in the main ASSP assembly as per the [documention](https://asstoredprocedures.github.io/functions/SQLQuery/) it is in it's own project for security reasons. You will need to compile the SqlQuery project to get that dll.

**Comment by bullsrl** [comment]
Hi Darren,

Thanks for the quick reply, makes sense and it works well, I had assumed that it was an option to deploy separately and we all you what assumptions make out of us :-)

Cheers

James
